version: '3.9'

services:
  mysql:
    container_name: org_db
    image: mysql:8.0
    volumes:
      - ./docker/snapshot:/tmp/snapshot
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "${DB_PORT}:3306"

  wordpress:
    container_name: org_wp
    depends_on:
      - mysql
    image: wordpress:php8.2-apache
    ports:
      - "${WP_PORT}:80"
    restart: "no"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG}"
    volumes:
      - ./docker/snapshot:/tmp/snapshot
      - ./docker/plugins:/var/www/html/wp-content/plugins
      - ./origamiez:/var/www/html/wp-content/themes/origamiez
      - type: bind
        source: ./docker/config/php.ini
        target: /usr/local/etc/php/php.ini
volumes:
  docker: {}